Map<String, Map<String, String>> countryCodes = {
  'Afghanistan': {'fullName': 'Afghanistan', 'alpha2': 'AF', 'alpha3': 'AFG'},
  'Albania': {'fullName': 'Albania', 'alpha2': 'AL', 'alpha3': 'ALB'},
  'Algeria': {'fullName': 'Algeria', 'alpha2': 'DZ', 'alpha3': 'DZA'},
  'American Samoa': {'fullName': 'American Samoa', 'alpha2': 'AS', 'alpha3': 'ASM'},
  'Andorra': {'fullName': 'Andorra', 'alpha2': 'AD', 'alpha3': 'AND'},
  'Angola': {'fullName': 'Angola', 'alpha2': 'AO', 'alpha3': 'AGO'},
  'Anguilla': {'fullName': 'Anguilla', 'alpha2': 'AI', 'alpha3': 'AIA'},
  'Antarctica': {'fullName': 'Antarctica', 'alpha2': 'AQ', 'alpha3': 'ATA'},
  'Antigua and Barbuda': {'fullName': 'Antigua and Barbuda', 'alpha2': 'AG', 'alpha3': 'ATG'},
  'Argentina': {'fullName': 'Argentina', 'alpha2': 'AR', 'alpha3': 'ARG'},
  'Armenia': {'fullName': 'Armenia', 'alpha2': 'AM', 'alpha3': 'ARM'},
  'Aruba': {'fullName': 'Aruba', 'alpha2': 'AW', 'alpha3': 'ABW'},
  'Australia': {'fullName': 'Australia', 'alpha2': 'AU', 'alpha3': 'AUS'},
  'Austria': {'fullName': 'Austria', 'alpha2': 'AT', 'alpha3': 'AUT'},
  'Azerbaijan': {'fullName': 'Azerbaijan', 'alpha2': 'AZ', 'alpha3': 'AZE'},
  'Bahamas': {'fullName': 'Bahamas', 'alpha2': 'BS', 'alpha3': 'BHS'},
  'Bahrain': {'fullName': 'Bahrain', 'alpha2': 'BH', 'alpha3': 'BHR'},
  'Bangladesh': {'fullName': 'Bangladesh', 'alpha2': 'BD', 'alpha3': 'BGD'},
  'Barbados': {'fullName': 'Barbados', 'alpha2': 'BB', 'alpha3': 'BRB'},
  'Belarus': {'fullName': 'Belarus', 'alpha2': 'BY', 'alpha3': 'BLR'},
  'Belgium': {'fullName': 'Belgium', 'alpha2': 'BE', 'alpha3': 'BEL'},
  'Belize': {'fullName': 'Belize', 'alpha2': 'BZ', 'alpha3': 'BLZ'},
  'Benin': {'fullName': 'Benin', 'alpha2': 'BJ', 'alpha3': 'BEN'},
  'Bermuda': {'fullName': 'Bermuda', 'alpha2': 'BM', 'alpha3': 'BMU'},
  'Bhutan': {'fullName': 'Bhutan', 'alpha2': 'BT', 'alpha3': 'BTN'},
  'Bolivia': {'fullName': 'Bolivia', 'alpha2': 'BO', 'alpha3': 'BOL'},
  'Bosnia and Herzegovina': {'fullName': 'Bosnia and Herzegovina', 'alpha2': 'BA', 'alpha3': 'BIH'},
  'Botswana': {'fullName': 'Botswana', 'alpha2': 'BW', 'alpha3': 'BWA'},
  'Brazil': {'fullName': 'Brazil', 'alpha2': 'BR', 'alpha3': 'BRA'},
  'British Indian Ocean Territory': {'fullName': 'British Indian Ocean Territory', 'alpha2': 'IO', 'alpha3': 'IOT'},
  'British Virgin Islands': {'fullName': 'British Virgin Islands', 'alpha2': 'VG', 'alpha3': 'VGB'},
  'Brunei': {'fullName': 'Brunei', 'alpha2': 'BN', 'alpha3': 'BRN'},
  'Bulgaria': {'fullName': 'Bulgaria', 'alpha2': 'BG', 'alpha3': 'BGR'},
  'Burkina Faso': {'fullName': 'Burkina Faso', 'alpha2': 'BF', 'alpha3': 'BFA'},
  'Burundi': {'fullName': 'Burundi', 'alpha2': 'BI', 'alpha3': 'BDI'},
  'Cambodia': {'fullName': 'Cambodia', 'alpha2': 'KH', 'alpha3': 'KHM'},
  'Cameroon': {'fullName': 'Cameroon', 'alpha2': 'CM', 'alpha3': 'CMR'},
  'Canada': {'fullName': 'Canada', 'alpha2': 'CA', 'alpha3': 'CAN'},
  'Cape Verde': {'fullName': 'Cape Verde', 'alpha2': 'CV', 'alpha3': 'CPV'},
  'Cayman Islands': {'fullName': 'Cayman Islands', 'alpha2': 'KY', 'alpha3': 'CYM'},
  'Central African Republic': {'fullName': 'Central African Republic', 'alpha2': 'CF', 'alpha3': 'CAF'},
  'Chad': {'fullName': 'Chad', 'alpha2': 'TD', 'alpha3': 'TCD'},
  'Chile': {'fullName': 'Chile', 'alpha2': 'CL', 'alpha3': 'CHL'},
  'China': {'fullName': 'China', 'alpha2': 'CN', 'alpha3': 'CHN'},
  'Christmas Island': {'fullName': 'Christmas Island', 'alpha2': 'CX', 'alpha3': 'CXR'},
  'Cocos Islands': {'fullName': 'Cocos Islands', 'alpha2': 'CC', 'alpha3': 'CCK'},
  'Colombia': {'fullName': 'Colombia', 'alpha2': 'CO', 'alpha3': 'COL'},
  'Comoros': {'fullName': 'Comoros', 'alpha2': 'KM', 'alpha3': 'COM'},
  'Cook Islands': {'fullName': 'Cook Islands', 'alpha2': 'CK', 'alpha3': 'COK'},
  'Costa Rica': {'fullName': 'Costa Rica', 'alpha2': 'CR', 'alpha3': 'CRI'},
  'Croatia': {'fullName': 'Croatia', 'alpha2': 'HR', 'alpha3': 'HRV'},
  'Cuba': {'fullName': 'Cuba', 'alpha2': 'CU', 'alpha3': 'CUB'},
  'Curacao': {'fullName': 'Curacao', 'alpha2': 'CW', 'alpha3': 'CUW'},
  'Cyprus': {'fullName': 'Cyprus', 'alpha2': 'CY', 'alpha3': 'CYP'},
  'Czech Republic': {'fullName': 'Czech Republic', 'alpha2': 'CZ', 'alpha3': 'CZE'},
  'Democratic Republic of the Congo': {'fullName': 'Democratic Republic of the Congo', 'alpha2': 'CD', 'alpha3': 'COD'},
  'Denmark': {'fullName': 'Denmark', 'alpha2': 'DK', 'alpha3': 'DNK'},
  'Djibouti': {'fullName': 'Djibouti', 'alpha2': 'DJ', 'alpha3': 'DJI'},
  'Dominica': {'fullName': 'Dominica', 'alpha2': 'DM', 'alpha3': 'DMA'},
  'Dominican Republic': {'fullName': 'Dominican Republic', 'alpha2': 'DO', 'alpha3': 'DOM'},
  'East Timor': {'fullName': 'East Timor', 'alpha2': 'TL', 'alpha3': 'TLS'},
  'Ecuador': {'fullName': 'Ecuador', 'alpha2': 'EC', 'alpha3': 'ECU'},
  'Egypt': {'fullName': 'Egypt', 'alpha2': 'EG', 'alpha3': 'EGY'},
  'El Salvador': {'fullName': 'El Salvador', 'alpha2': 'SV', 'alpha3': 'SLV'},
  'Equatorial Guinea': {'fullName': 'Equatorial Guinea', 'alpha2': 'GQ', 'alpha3': 'GNQ'},
  'Eritrea': {'fullName': 'Eritrea', 'alpha2': 'ER', 'alpha3': 'ERI'},
  'Estonia': {'fullName': 'Estonia', 'alpha2': 'EE', 'alpha3': 'EST'},
  'Ethiopia': {'fullName': 'Ethiopia', 'alpha2': 'ET', 'alpha3': 'ETH'},
  'Falkland Islands': {'fullName': 'Falkland Islands', 'alpha2': 'FK', 'alpha3': 'FLK'},
  'Faroe Islands': {'fullName': 'Faroe Islands', 'alpha2': 'FO', 'alpha3': 'FRO'},
  'Fiji': {'fullName': 'Fiji', 'alpha2': 'FJ', 'alpha3': 'FJI'},
  'Finland': {'fullName': 'Finland', 'alpha2': 'FI', 'alpha3': 'FIN'},
  'France': {'fullName': 'France', 'alpha2': 'FR', 'alpha3': 'FRA'},
  'French Polynesia': {'fullName': 'French Polynesia', 'alpha2': 'PF', 'alpha3': 'PYF'},
  'Gabon': {'fullName': 'Gabon', 'alpha2': 'GA', 'alpha3': 'GAB'},
  'Gambia': {'fullName': 'Gambia', 'alpha2': 'GM', 'alpha3': 'GMB'},
  'Georgia': {'fullName': 'Georgia', 'alpha2': 'GE', 'alpha3': 'GEO'},
  'Germany': {'fullName': 'Germany', 'alpha2': 'DE', 'alpha3': 'DEU'},
  'Ghana': {'fullName': 'Ghana', 'alpha2': 'GH', 'alpha3': 'GHA'},
  'Gibraltar': {'fullName': 'Gibraltar', 'alpha2': 'GI', 'alpha3': 'GIB'},
  'Greece': {'fullName': 'Greece', 'alpha2': 'GR', 'alpha3': 'GRC'},
  'Greenland': {'fullName': 'Greenland', 'alpha2': 'GL', 'alpha3': 'GRL'},
  'Grenada': {'fullName': 'Grenada', 'alpha2': 'GD', 'alpha3': 'GRD'},
  'Guam': {'fullName': 'Guam', 'alpha2': 'GU', 'alpha3': 'GUM'},
  'Guatemala': {'fullName': 'Guatemala', 'alpha2': 'GT', 'alpha3': 'GTM'},
  'Guernsey': {'fullName': 'Guernsey', 'alpha2': 'GG', 'alpha3': 'GGY'},
  'Guinea': {'fullName': 'Guinea', 'alpha2': 'GN', 'alpha3': 'GIN'},
  'Guinea-Bissau': {'fullName': 'Guinea-Bissau', 'alpha2': 'GW', 'alpha3': 'GNB'},
  'Guyana': {'fullName': 'Guyana', 'alpha2': 'GY', 'alpha3': 'GUY'},
  'Haiti': {'fullName': 'Haiti', 'alpha2': 'HT', 'alpha3': 'HTI'},
  'Honduras': {'fullName': 'Honduras', 'alpha2': 'HN', 'alpha3': 'HND'},
  'Hong Kong': {'fullName': 'Hong Kong', 'alpha2': 'HK', 'alpha3': 'HKG'},
  'Hungary': {'fullName': 'Hungary', 'alpha2': 'HU', 'alpha3': 'HUN'},
  'Iceland': {'fullName': 'Iceland', 'alpha2': 'IS', 'alpha3': 'ISL'},
  'India': {'fullName': 'India', 'alpha2': 'IN', 'alpha3': 'IND'},
  'Indonesia': {'fullName': 'Indonesia', 'alpha2': 'ID', 'alpha3': 'IDN'},
  'Iran': {'fullName': 'Iran', 'alpha2': 'IR', 'alpha3': 'IRN'},
  'Iraq': {'fullName': 'Iraq', 'alpha2': 'IQ', 'alpha3': 'IRQ'},
  'Ireland': {'fullName': 'Ireland', 'alpha2': 'IE', 'alpha3': 'IRL'},
  'Isle of Man': {'fullName': 'Isle of Man', 'alpha2': 'IM', 'alpha3': 'IMN'},
  'Israel': {'fullName': 'Israel', 'alpha2': 'IL', 'alpha3': 'ISR'},
  'Italy': {'fullName': 'Italy', 'alpha2': 'IT', 'alpha3': 'ITA'},
  'Ivory Coast': {'fullName': 'Ivory Coast', 'alpha2': 'CI', 'alpha3': 'CIV'},
  'Jamaica': {'fullName': 'Jamaica', 'alpha2': 'JM', 'alpha3': 'JAM'},
  'Japan': {'fullName': 'Japan', 'alpha2': 'JP', 'alpha3': 'JPN'},
  'Jersey': {'fullName': 'Jersey', 'alpha2': 'JE', 'alpha3': 'JEY'},
  'Jordan': {'fullName': 'Jordan', 'alpha2': 'JO', 'alpha3': 'JOR'},
  'Kazakhstan': {'fullName': 'Kazakhstan', 'alpha2': 'KZ', 'alpha3': 'KAZ'},
  'Kenya': {'fullName': 'Kenya', 'alpha2': 'KE', 'alpha3': 'KEN'},
  'Kiribati': {'fullName': 'Kiribati', 'alpha2': 'KI', 'alpha3': 'KIR'},
  'Kosovo': {'fullName': 'Kosovo', 'alpha2': 'XK', 'alpha3': 'XKX'},
  'Kuwait': {'fullName': 'Kuwait', 'alpha2': 'KW', 'alpha3': 'KWT'},
  'Kyrgyzstan': {'fullName': 'Kyrgyzstan', 'alpha2': 'KG', 'alpha3': 'KGZ'},
  'Laos': {'fullName': 'Laos', 'alpha2': 'LA', 'alpha3': 'LAO'},
  'Latvia': {'fullName': 'Latvia', 'alpha2': 'LV', 'alpha3': 'LVA'},
  'Lebanon': {'fullName': 'Lebanon', 'alpha2': 'LB', 'alpha3': 'LBN'},
  'Lesotho': {'fullName': 'Lesotho', 'alpha2': 'LS', 'alpha3': 'LSO'},
  'Liberia': {'fullName': 'Liberia', 'alpha2': 'LR', 'alpha3': 'LBR'},
  'Libya': {'fullName': 'Libya', 'alpha2': 'LY', 'alpha3': 'LBY'},
  'Liechtenstein': {'fullName': 'Liechtenstein', 'alpha2': 'LI', 'alpha3': 'LIE'},
  'Lithuania': {'fullName': 'Lithuania', 'alpha2': 'LT', 'alpha3': 'LTU'},
  'Luxembourg': {'fullName': 'Luxembourg', 'alpha2': 'LU', 'alpha3': 'LUX'},
  'Macau': {'fullName': 'Macau', 'alpha2': 'MO', 'alpha3': 'MAC'},
  'Macedonia': {'fullName': 'Macedonia', 'alpha2': 'MK', 'alpha3': 'MKD'},
  'Madagascar': {'fullName': 'Madagascar', 'alpha2': 'MG', 'alpha3': 'MDG'},
  'Malawi': {'fullName': 'Malawi', 'alpha2': 'MW', 'alpha3': 'MWI'},
  'Malaysia': {'fullName': 'Malaysia', 'alpha2': 'MY', 'alpha3': 'MYS'},
  'Maldives': {'fullName': 'Maldives', 'alpha2': 'MV', 'alpha3': 'MDV'},
  'Mali': {'fullName': 'Mali', 'alpha2': 'ML', 'alpha3': 'MLI'},
  'Malta': {'fullName': 'Malta', 'alpha2': 'MT', 'alpha3': 'MLT'},
  'Marshall Islands': {'fullName': 'Marshall Islands', 'alpha2': 'MH', 'alpha3': 'MHL'},
  'Mauritania': {'fullName': 'Mauritania', 'alpha2': 'MR', 'alpha3': 'MRT'},
  'Mauritius': {'fullName': 'Mauritius', 'alpha2': 'MU', 'alpha3': 'MUS'},
  'Mayotte': {'fullName': 'Mayotte', 'alpha2': 'YT', 'alpha3': 'MYT'},
  'Mexico': {'fullName': 'Mexico', 'alpha2': 'MX', 'alpha3': 'MEX'},
  'Micronesia': {'fullName': 'Micronesia', 'alpha2': 'FM', 'alpha3': 'FSM'},
  'Moldova': {'fullName': 'Moldova', 'alpha2': 'MD', 'alpha3': 'MDA'},
  'Monaco': {'fullName': 'Monaco', 'alpha2': 'MC', 'alpha3': 'MCO'},
  'Mongolia': {'fullName': 'Mongolia', 'alpha2': 'MN', 'alpha3': 'MNG'},
  'Montenegro': {'fullName': 'Montenegro', 'alpha2': 'ME', 'alpha3': 'MNE'},
  'Montserrat': {'fullName': 'Montserrat', 'alpha2': 'MS', 'alpha3': 'MSR'},
  'Morocco': {'fullName': 'Morocco', 'alpha2': 'MA', 'alpha3': 'MAR'},
  'Mozambique': {'fullName': 'Mozambique', 'alpha2': 'MZ', 'alpha3': 'MOZ'},
  'Myanmar': {'fullName': 'Myanmar', 'alpha2': 'MM', 'alpha3': 'MMR'},
  'Namibia': {'fullName': 'Namibia', 'alpha2': 'NA', 'alpha3': 'NAM'},
  'Nauru': {'fullName': 'Nauru', 'alpha2': 'NR', 'alpha3': 'NRU'},
  'Nepal': {'fullName': 'Nepal', 'alpha2': 'NP', 'alpha3': 'NPL'},
  'Netherlands': {'fullName': 'Netherlands', 'alpha2': 'NL', 'alpha3': 'NLD'},
  'Netherlands Antilles': {'fullName': 'Netherlands Antilles', 'alpha2': 'AN', 'alpha3': 'ANT'},
  'New Caledonia': {'fullName': 'New Caledonia', 'alpha2': 'NC', 'alpha3': 'NCL'},
  'New Zealand': {'fullName': 'New Zealand', 'alpha2': 'NZ', 'alpha3': 'NZL'},
  'Nicaragua': {'fullName': 'Nicaragua', 'alpha2': 'NI', 'alpha3': 'NIC'},
  'Niger': {'fullName': 'Niger', 'alpha2': 'NE', 'alpha3': 'NER'},
  'Nigeria': {'fullName': 'Nigeria', 'alpha2': 'NG', 'alpha3': 'NGA'},
  'Niue': {'fullName': 'Niue', 'alpha2': 'NU', 'alpha3': 'NIU'},
  'North Korea': {'fullName': 'North Korea', 'alpha2': 'KP', 'alpha3': 'PRK'},
  'Northern Mariana Islands': {'fullName': 'Northern Mariana Islands', 'alpha2': 'MP', 'alpha3': 'MNP'},
  'Norway': {'fullName': 'Norway', 'alpha2': 'NO', 'alpha3': 'NOR'},
  'Oman': {'fullName': 'Oman', 'alpha2': 'OM', 'alpha3': 'OMN'},
  'Pakistan': {'fullName': 'Pakistan', 'alpha2': 'PK', 'alpha3': 'PAK'},
  'Palau': {'fullName': 'Palau', 'alpha2': 'PW', 'alpha3': 'PLW'},
  'Palestine': {'fullName': 'Palestine', 'alpha2': 'PS', 'alpha3': 'PSE'},
  'Panama': {'fullName': 'Panama', 'alpha2': 'PA', 'alpha3': 'PAN'},
  'Papua New Guinea': {'fullName': 'Papua New Guinea', 'alpha2': 'PG', 'alpha3': 'PNG'},
  'Paraguay': {'fullName': 'Paraguay', 'alpha2': 'PY', 'alpha3': 'PRY'},
  'Peru': {'fullName': 'Peru', 'alpha2': 'PE', 'alpha3': 'PER'},
  'Philippines': {'fullName': 'Philippines', 'alpha2': 'PH', 'alpha3': 'PHL'},
  'Pitcairn Islands': {'fullName': 'Pitcairn Islands', 'alpha2': 'PN', 'alpha3': 'PCN'},
  'Poland': {'fullName': 'Poland', 'alpha2': 'PL', 'alpha3': 'POL'},
  'Portugal': {'fullName': 'Portugal', 'alpha2': 'PT', 'alpha3': 'PRT'},
  'Puerto Rico': {'fullName': 'Puerto Rico', 'alpha2': 'PR', 'alpha3': 'PRI'},
  'Qatar': {'fullName': 'Qatar', 'alpha2': 'QA', 'alpha3': 'QAT'},
  'Republic of the Congo': {'fullName': 'Republic of the Congo', 'alpha2': 'CG', 'alpha3': 'COG'},
  'Reunion': {'fullName': 'Reunion', 'alpha2': 'RE', 'alpha3': 'REU'},
  'Romania': {'fullName': 'Romania', 'alpha2': 'RO', 'alpha3': 'ROU'},
  'Russia': {'fullName': 'Russia', 'alpha2': 'RU', 'alpha3': 'RUS'},
  'Rwanda': {'fullName': 'Rwanda', 'alpha2': 'RW', 'alpha3': 'RWA'},
  'Saint Barthelemy': {'fullName': 'Saint Barthelemy', 'alpha2': 'BL', 'alpha3': 'BLM'},
  'Saint Helena': {'fullName': 'Saint Helena', 'alpha2': 'SH', 'alpha3': 'SHN'},
  'Saint Kitts and Nevis': {'fullName': 'Saint Kitts and Nevis', 'alpha2': 'KN', 'alpha3': 'KNA'},
  'Saint Lucia': {'fullName': 'Saint Lucia', 'alpha2': 'LC', 'alpha3': 'LCA'},
  'Saint Martin': {'fullName': 'Saint Martin', 'alpha2': 'MF', 'alpha3': 'MAF'},
  'Saint Pierre and Miquelon': {'fullName': 'Saint Pierre and Miquelon', 'alpha2': 'PM', 'alpha3': 'SPM'},
  'Saint Vincent and the Grenadines': {'fullName': 'Saint Vincent and the Grenadines', 'alpha2': 'VC', 'alpha3': 'VCT'},
  'Samoa': {'fullName': 'Samoa', 'alpha2': 'WS', 'alpha3': 'WSM'},
  'San Marino': {'fullName': 'San Marino', 'alpha2': 'SM', 'alpha3': 'SMR'},
  'Sao Tome and Principe': {'fullName': 'Sao Tome and Principe', 'alpha2': 'ST', 'alpha3': 'STP'},
  'Saudi Arabia': {'fullName': 'Saudi Arabia', 'alpha2': 'SA', 'alpha3': 'SAU'},
  'Senegal': {'fullName': 'Senegal', 'alpha2': 'SN', 'alpha3': 'SEN'},
  'Serbia': {'fullName': 'Serbia', 'alpha2': 'RS', 'alpha3': 'SRB'},
  'Seychelles': {'fullName': 'Seychelles', 'alpha2': 'SC', 'alpha3': 'SYC'},
  'Sierra Leone': {'fullName': 'Sierra Leone', 'alpha2': 'SL', 'alpha3': 'SLE'},
  'Singapore': {'fullName': 'Singapore', 'alpha2': 'SG', 'alpha3': 'SGP'},
  'Sint Maarten': {'fullName': 'Sint Maarten', 'alpha2': 'SX', 'alpha3': 'SXM'},
  'Slovakia': {'fullName': 'Slovakia', 'alpha2': 'SK', 'alpha3': 'SVK'},
  'Slovenia': {'fullName': 'Slovenia', 'alpha2': 'SI', 'alpha3': 'SVN'},
  'Solomon Islands': {'fullName': 'Solomon Islands', 'alpha2': 'SB', 'alpha3': 'SLB'},
  'Somalia': {'fullName': 'Somalia', 'alpha2': 'SO', 'alpha3': 'SOM'},
  'South Africa': {'fullName': 'South Africa', 'alpha2': 'ZA', 'alpha3': 'ZAF'},
  'South Korea': {'fullName': 'South Korea', 'alpha2': 'KR', 'alpha3': 'KOR'},
  'South Sudan': {'fullName': 'South Sudan', 'alpha2': 'SS', 'alpha3': 'SSD'},
  'Spain': {'fullName': 'Spain', 'alpha2': 'ES', 'alpha3': 'ESP'},
  'Sri Lanka': {'fullName': 'Sri Lanka', 'alpha2': 'LK', 'alpha3': 'LKA'},
  'Sudan': {'fullName': 'Sudan', 'alpha2': 'SD', 'alpha3': 'SDN'},
  'Suriname': {'fullName': 'Suriname', 'alpha2': 'SR', 'alpha3': 'SUR'},
  'Svalbard and Jan Mayen': {'fullName': 'Svalbard and Jan Mayen', 'alpha2': 'SJ', 'alpha3': 'SJM'},
  'Swaziland': {'fullName': 'Swaziland', 'alpha2': 'SZ', 'alpha3': 'SWZ'},
  'Sweden': {'fullName': 'Sweden', 'alpha2': 'SE', 'alpha3': 'SWE'},
  'Switzerland': {'fullName': 'Switzerland', 'alpha2': 'CH', 'alpha3': 'CHE'},
  'Syria': {'fullName': 'Syria', 'alpha2': 'SY', 'alpha3': 'SYR'},
  'Taiwan': {'fullName': 'Taiwan', 'alpha2': 'TW', 'alpha3': 'TWN'},
  'Tajikistan': {'fullName': 'Tajikistan', 'alpha2': 'TJ', 'alpha3': 'TJK'},
  'Tanzania': {'fullName': 'Tanzania', 'alpha2': 'TZ', 'alpha3': 'TZA'},
  'Thailand': {'fullName': 'Thailand', 'alpha2': 'TH', 'alpha3': 'THA'},
  'Togo': {'fullName': 'Togo', 'alpha2': 'TG', 'alpha3': 'TGO'},
  'Tokelau': {'fullName': 'Tokelau', 'alpha2': 'TK', 'alpha3': 'TKL'},
  'Tonga': {'fullName': 'Tonga', 'alpha2': 'TO', 'alpha3': 'TON'},
  'Trinidad and Tobago': {'fullName': 'Trinidad and Tobago', 'alpha2': 'TT', 'alpha3': 'TTO'},
  'Tunisia': {'fullName': 'Tunisia', 'alpha2': 'TN', 'alpha3': 'TUN'},
  'Turkey': {'fullName': 'Turkey', 'alpha2': 'TR', 'alpha3': 'TUR'},
  'Turkmenistan': {'fullName': 'Turkmenistan', 'alpha2': 'TM', 'alpha3': 'TKM'},
  'Turks and Caicos Islands': {'fullName': 'Turks and Caicos Islands', 'alpha2': 'TC', 'alpha3': 'TCA'},
  'Tuvalu': {'fullName': 'Tuvalu', 'alpha2': 'TV', 'alpha3': 'TUV'},
  'Uganda': {'fullName': 'Uganda', 'alpha2': 'UG', 'alpha3': 'UGA'},
  'Ukraine': {'fullName': 'Ukraine', 'alpha2': 'UA', 'alpha3': 'UKR'},
  'United Arab Emirates': {'fullName': 'United Arab Emirates', 'alpha2': 'AE', 'alpha3': 'ARE'},
  'United Kingdom': {'fullName': 'United Kingdom', 'alpha2': 'GB', 'alpha3': 'GBR'},
  'United States': {'fullName': 'United States', 'alpha2': 'US', 'alpha3': 'USA'},
  'Uruguay': {'fullName': 'Uruguay', 'alpha2': 'UY', 'alpha3': 'URY'},
  'Uzbekistan': {'fullName': 'Uzbekistan', 'alpha2': 'UZ', 'alpha3': 'UZB'},
  'Vanuatu': {'fullName': 'Vanuatu', 'alpha2': 'VU', 'alpha3': 'VUT'},
  'Vatican': {'fullName': 'Vatican', 'alpha2': 'VA', 'alpha3': 'VAT'},
  'Venezuela': {'fullName': 'Venezuela', 'alpha2': 'VE', 'alpha3': 'VEN'},
  'Vietnam': {'fullName': 'Vietnam', 'alpha2': 'VN', 'alpha3': 'VNM'},
  'Wallis and Futuna': {'fullName': 'Wallis and Futuna', 'alpha2': 'WF', 'alpha3': 'WLF'},
  'Western Sahara': {'fullName': 'Western Sahara', 'alpha2': 'EH', 'alpha3': 'ESH'},
  'Yemen': {'fullName': 'Yemen', 'alpha2': 'YE', 'alpha3': 'YEM'},
  'Zambia': {'fullName': 'Zambia', 'alpha2': 'ZM', 'alpha3': 'ZMB'},
  'Zimbabwe': {'fullName': 'Zimbabwe', 'alpha2': 'ZW', 'alpha3': 'ZWE'}
};



